from typing import Annotated

from fastapi import APIRouter, HTTPException, Path, status

from app.dependencies import DbSession, CurrentUser, AdminUser
from app.models.basket import BasketItem
from app.models.order import Order, OrderItem, OrderStatus
from app.models.product import Product
from app.schemas.order import OrderResponse

router = APIRouter()

OrderId = Annotated[int, Path(description="Order ID")]


@router.get(
    "/",
    response_model=list[OrderResponse]
)
def get_orders(
    current_user: CurrentUser,
    db: DbSession,
):
    orders = (
        db.query(Order)
        .filter(Order.user_id == current_user.id)
        .order_by(Order.created_at.desc())
        .all()
    )
    return orders


@router.get(
    "/{order_id}",
    response_model=OrderResponse
)
def get_order(
    order_id: OrderId,
    current_user: CurrentUser,
    db: DbSession,
):
    order = (
        db.query(Order)
        .filter(
            Order.id == order_id,
            Order.user_id == current_user.id,
        )
        .first()
    )
    if not order:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order {order_id} not found",
        )
    return order


@router.post(
    "/",
    response_model=OrderResponse,
    status_code=status.HTTP_201_CREATED
)
def create_order(
    current_user: CurrentUser,
    db: DbSession,
):
    """Creates an order from the basket. The SQLAlchemy commands are as follows:
        db.add(order)       → order.id is None
        db.flush()          → order.id is now e.g. 42, but not committed (only in-memory)
        db.add(order_item)  → uses order.id = 42
        db.add(order_item)  → uses order.id = 42
        db.delete(basket)   → still in same transaction
        db.commit()         → everything saved atomically

    So we have the following:
        db.add():    the object only exists in Python memory; no SQL sent to the DB at all (need to use order.id).
        db.flush():  sends the INSERT SQL to the DB within the current transaction, so order.id generated by DB, but transaction is still open (nothing permanently saved yet)
                        therefore if something fails after this, the whole transaction rolls back.
        db.commit(): permanently saves everything and closes the transaction (after this, data is written and visible to other connections).
    """
    basket_items = (
        db.query(BasketItem)
        .filter(BasketItem.user_id == current_user.id)
        .all()
    )

    if not basket_items:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Basket is empty",
        )

    for basket_item in basket_items:
        product = db.get(Product, basket_item.product_id)
        if product.stock < basket_item.quantity:
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail=f"Insufficient stock for {product.name}, only {product.stock} units available",
            )

    total = sum(item.price_at_add * item.quantity for item in basket_items)

    order = Order(
        user_id=current_user.id,
        status=OrderStatus.pending,
        total=total,
    )
    db.add(order)
    db.flush()

    for basket_item in basket_items:
        order_item = OrderItem(
            order_id=order.id,
            product_id=basket_item.product_id,
            quantity=basket_item.quantity,
            price_at_purchase=basket_item.price_at_add,
        )
        db.add(order_item)

        product = db.get(Product, basket_item.product_id)
        product.stock -= basket_item.quantity

    db.query(BasketItem).filter(BasketItem.user_id == current_user.id).delete()

    db.commit()
    db.refresh(order)
    return order


@router.put(
    "/{order_id}/cancel",
    response_model=OrderResponse
)
def cancel_order(
    order_id: OrderId,
    current_user: CurrentUser,
    db: DbSession,
):
    order = (
        db.query(Order)
        .filter(
            Order.id == order_id,
            Order.user_id == current_user.id,
        )
        .first()
    )
    if not order:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Order {order_id} not found",
        )

    if order.status != OrderStatus.pending:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Order cannot be cancelled, current status is {order.status.value}",
        )

    for order_item in order.items:
        product = db.get(Product, order_item.product_id)
        product.stock += order_item.quantity

    order.status = OrderStatus.cancelled
    db.commit()
    db.refresh(order)
    return order
