"""add is_active to products

Revision ID: bb220cc6a6ee
Revises: b6da052fb5bf
Create Date: 2026-05-03 18:10:10.218922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb220cc6a6ee'
down_revision: Union[str, Sequence[str], None] = 'b6da052fb5bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # the service_default='1' is important for existing rows that do not have this column; it back-fills, '1' is TRUE
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
